Feature/guide
Trendravel/photoravel-fe pull request #4
Opened 2024-09-25 19:40 UTC by keemeunji

2024-09-26 00:16 UTC, Spooder02 requested changes
BottomSheet는 경로에 따라 동적으로 렌더링하는 방식이므로, 필터 및 검색 등의 기능들은 컴포넌트로 분리시키셔야 할 것 같습니다.

2024-09-26 00:21 UTC, Spooder02 reviewed
해당 reviews는 별도로 json 파일에 분리해두셔야 할 것 같습니다.

2024-09-26 00:44 UTC, Spooder02 commented on src/components/BottomSheet.tsx
BottomSheet는 경로에 따라 동적으로 렌더링하는 방식이므로, 필터 및 검색 등의 기능들은 컴포넌트로 분리하여 BottomSheet에 동적으로 렌더링할 수 있도록 수정하셔야 할 것 같습니다.

2024-09-26 00:44 UTC, Spooder02 commented on src/pages/GuidebookWrite.page.tsx
선언된 enum 타입도 types에 분리하여 주시면 좋을 것 같습니다!

2024-09-26 00:44 UTC, Spooder02 commented on src/pages/MatchingStatus.page.tsx
MatchingStatus 인터페이스가 이미 'types/MatchingInfo.tsx'에서 선언되어 있는 것으로 확인되어 별도 선언 없이, 해당 인터페이스를 불러와 사용해주시면 좋을 것 같습니다.

2024-09-27 08:27 UTC, keemeunji commented on src/pages/MatchingStatus.page.tsx
넵 수정했습니다!

2024-10-01 13:30 UTC, merged